-- public.account_twitter definition

-- Drop table

-- DROP TABLE public.account_twitter;

CREATE TABLE public.account_twitter (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	account_name varchar NULL,
	client_id varchar NULL,
	client_secret varchar NULL,
	"language" varchar NULL
);


-- public.game_list definition

-- Drop table

-- DROP TABLE public.game_list;

CREATE TABLE public.game_list (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	game_name varchar NULL,
	name_team_1 varchar NULL,
	name_team_2 varchar NULL,
	time_played time NULL,
	result_team_1 varchar NULL,
	result_team_2 varchar NULL,
	start_date timestamp NULL,
	end_date timestamp NULL,
	game_id_api varchar NULL
);


-- public.tweet_list definition

-- Drop table

-- DROP TABLE public.tweet_list;

CREATE TABLE public.tweet_list (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"language" varchar NULL,
	"content" varchar NULL,
	action_type varchar NULL
);


-- public.tweeted_list definition

-- Drop table

-- DROP TABLE public.tweeted_list;

CREATE TABLE public.tweeted_list (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	account_twitter_id varchar NULL,
	"content" varchar NULL,
	"language" varchar NULL,
	twitted_at timestamp NULL
);