tweet_goal = "Match {match}: nouveau but! Temps ecoule: {elapsed}"
tweet_start = "Debut du match {match}"
tweet_end = "Fin fu match {match}"
tweet_halftime_start = "Debut de la mi-temps {match}"
tweet_halftime_end = "Fin de la mi-temps {match}"
